Revert "Borro la carpeta de Models JSON,  Error: Cannot find module '../modelsJson/User'(error de Heroku)"
This reverts commit 95b006b0454d9a197318f7ac00a617b5d72ea284.